name: Deploy Multi-Project
on:
  push:
    branches: [main]

permissions:
  contents: write # Asegúrate de que este permiso esté activo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build Proyecto 1 (01-4-en-raya)
        run: |
          cd exercises/01-4-en-raya # Asegúrate de que la ruta sea correcta (ejercicios o exercises)
          npm install # INSTALA dependencias aquí
          npm run build
          # Mueve los archivos compilados a la carpeta pública
          mkdir -p ../../../public/01-4-en-raya
          cp -r dist/* ../../../public/01-4-en-raya/

      - name: Install and Build Proyecto 2 (02-random-bible-verses)
        run: |
          cd exercises/02-random-bible-verses # Asegúrate de que la ruta sea correcta
          npm install # INSTALA dependencias aquí
          npm run build
          # Mueve los archivos compilados a la carpeta pública
          mkdir -p ../../../public/02-random-bible-verses
          cp -r dist/* ../../../public/02-random-bible-verses

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
