name: Deploy Multi-Project
on:
  push:
    branches: [main]

permissions:
  contents: write # Asegúrate de que este permiso esté activo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install and Build Proyecto 1 (01-4-en-raya)
        run: |
          cd exercises/01-4-en-raya
          npm install
          npm run build
          # Subimos solo 2 niveles para llegar a la raíz del repo
          mkdir -p ../../public/01-4-en-raya
          cp -r dist/* ../../public/01-4-en-raya/

      - name: Install and Build Proyecto 2 (02-random-bible-verses)
        run: |
          cd exercises/02-random-bible-verses
          npm install
          npm run build
          # Subimos solo 2 niveles para llegar a la raíz del repo
          mkdir -p ../../public/02-random-bible-verses
          cp -r dist/* ../../public/02-random-bible-verses/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
